name: Build python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pushd src/python
        python -m pip install --upgrade pip
        pip install flake8 pytest build
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        popd
    - name: Build
      run: |
        pushd src/python
        python -m build
        python -m pip install .
        popd
    - name: Lint with flake8
      run: |
        pushd src/python
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        popd
    - name: Test with pytest
      run: |
        pushd src/python
        pytest        
        popd

  